name: "Go - Basic Checks"
on:
  push:
    branches: [ "trunk" ]
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', '1.21.x', '1.22.x' ]

    steps:
      - name: Download This Repository
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Build
        run: go build -v ./...

      - name: Generate
        run: go generate -v ./...

      - name: Vet
        run: go vet ./...
          
      - name: Test
        run: go test -v ./... -short
